
PLISTBUDDY=/usr/libexec/PlistBuddy

# Get the path to git
if [ -f /etc/profile ]; then
	source /etc/profile
fi
GIT=`which git`
if [ -f /opt/local/bin/git ]; then
	GIT="/opt/local/bin/git"
fi
echo "----> GIT=${GIT}"

# Make sure GIT is not an empty string -z, otherwise we don't have the path to git :)
if [ -z ${GIT} ]; then
	echo ' ***** Cannot find git, make sure it is in your PATH envirnoment variable. *****'
	exit 1
fi

# Get the short commit hash (i.e. bc917e0)
SHA=`${GIT} rev-parse --short HEAD`
echo "----> SHA=${SHA}"

# Any changes to the working directory?  Did the developer monkey around with the code before building? 
# $ git diff --quiet   # it exits with 1 if there were differences and 0 means no differences.

if ! ${GIT} diff --quiet
	then # there have been changes to working directory that have not been commited
	SHA="${SHA}*"  # append * to the commit hash to note the uncommitted changes
	echo "----> *** We have changes to the code ***"
fi

# Dump the output to a file

filepath="${SRCROOT}/src/main/Scripts/git_version_hash.h"

echo "// This file is automatically generated" > ${filepath}
echo "#define GIT_COMMIT_HASH \"$SHA\"" >> ${filepath}
echo "#define BUILD_DATE \"$(date "+%Y-%m-%d %H:%M:%S")\"" >> ${filepath}

 